# Generated by Django 5.0.1 on 2026-03-24 20:32

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимый')),
                ('is_frozen', models.BooleanField(default=False, verbose_name='Заморожен')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Чат',
                'verbose_name_plural': 'Чаты',
            },
        ),
        migrations.CreateModel(
            name='GlobalFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(verbose_name='Паттерн (regex)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Глобальный фильтр',
                'verbose_name_plural': 'Глобальные фильтры',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('profile_type', models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Руководитель'), ('employee', 'Сотрудник')], default='employee', max_length=50, verbose_name='Тип профиля')),
                ('connect_token', models.CharField(default=main.models._generate_token, max_length=64, unique=True, verbose_name='Токен подключения')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='UserTelegram',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Id пользователя')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юзернэйм')),
                ('appeal_time', models.DateTimeField(verbose_name='Дата последнего обращения')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_block', models.BooleanField(default=False, verbose_name='Блокировка')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Telegram Пользователь',
                'verbose_name_plural': 'Telegram Пользователи',
            },
        ),
        migrations.CreateModel(
            name='ChatFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.TextField(verbose_name='Паттерн (regex)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='main.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Фильтр чата',
                'verbose_name_plural': 'Фильтры чатов',
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connect_token', models.CharField(default=main.models._generate_member_token, max_length=64, unique=True, verbose_name='Токен подключения')),
                ('member_type', models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор'), ('manager', 'Руководитель'), ('employee', 'Сотрудник')], default='client', max_length=50, verbose_name='Тип участника')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заморожен')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='main.chat', verbose_name='Чат')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='main.profile', verbose_name='Профиль')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='main.usertelegram', verbose_name='Telegram пользователь')),
            ],
            options={
                'verbose_name': 'Участник чата',
                'verbose_name_plural': 'Участники чатов',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('has_forbidden', models.BooleanField(default=False, verbose_name='Содержит запрещённые материалы')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.chatmember', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_file', models.CharField(max_length=512, verbose_name='File ID (Telegram)')),
                ('attachment_type', models.CharField(choices=[('photo', 'Фото'), ('video', 'Видео'), ('audio', 'Аудио'), ('voice', 'Голосовое'), ('document', 'Документ'), ('video_note', 'Видеокружок'), ('sticker', 'Стикер')], default='document', max_length=50, verbose_name='Тип вложения')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='main.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_chats', to='main.profile', verbose_name='Создатель'),
        ),
        migrations.CreateModel(
            name='AutoConnect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_connects', to='main.profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Автоподключение',
                'verbose_name_plural': 'Автоподключения',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='main.usertelegram', verbose_name='Telegram аккаунт'),
        ),
        migrations.CreateModel(
            name='DataState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Состояние')),
                ('data', models.BinaryField(blank=True, null=True, verbose_name='Данные состояния')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_state', to='main.usertelegram', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Состояние пользователя',
                'verbose_name_plural': 'Состояния пользователей',
            },
        ),
    ]
