# Generated by Django 5.0.1 on 2026-03-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег участника'),
        ),
    ]
