# Generated by Django 5.0.1 on 2026-03-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admin_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание админа'),
        ),
    ]
