# Generated by Django 5.0.1 on 2026-03-26 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_chat_admin_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='main.company'),
        ),
    ]
