# Generated by Django 5.0.1 on 2026-03-27 12:02

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_chatmember_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('rules', 'Правила / Приветствие')], default='rules', max_length=50, verbose_name='Тип текста')),
                ('title', models.CharField(help_text='Служебное название — видно только в админке', max_length=255, verbose_name='Заголовок (для ориентира)')),
                ('content', models.TextField(help_text='Поддерживается HTML-разметка Telegram: <b>, <i>, <code>, <a href=...>', verbose_name='Текст (HTML)')),
                ('is_active', models.BooleanField(default=True, help_text='Только один активный текст одного типа будет использоваться ботом', verbose_name='Активен')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Текст бота',
                'verbose_name_plural': 'Тексты бота',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания (заказчик)', 'verbose_name_plural': 'Компании (заказчики)'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_create'], 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='chat',
            name='admin_description',
            field=models.TextField(blank=True, help_text='Видно только администраторам и руководителям', null=True, verbose_name='Описание (приватное)'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (общее)'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тег (псевдоним)'),
        ),
        migrations.AlterField(
            model_name='chatmember',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='main.company', verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_blocked',
            field=models.BooleanField(default=False, verbose_name='Заблокирована'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.CreateModel(
            name='ChatInviteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=main.models._generate_invite_token, max_length=64, unique=True, verbose_name='Токен')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_links', to='main.chat', verbose_name='Чат')),
            ],
            options={
                'verbose_name': 'Ссылка-приглашение',
                'verbose_name_plural': 'Ссылки-приглашения',
            },
        ),
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_message_id', models.IntegerField(default=0, verbose_name='ID последнего прочитанного сообщения')),
                ('date_read', models.DateTimeField(auto_now=True, verbose_name='Дата последнего прочтения')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='read_mark', to='main.chatmember', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Отметка о прочтении',
                'verbose_name_plural': 'Отметки о прочтении',
            },
        ),
    ]
