# Generated by Django 5.0.1 on 2026-03-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bottext_alter_company_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='company_mode',
            field=models.BooleanField(default=True, verbose_name='Режим компании'),
        ),
    ]
